// This file contains the complete azkar data shared between the main route and search API
// It's extracted from the main route file to ensure consistency

export const completeAzkarData = {
  morning: {
    category: {
      id: "1",
      name: "Morning",
      nameAr: "أذكار الصباح",
      description: "Morning remembrance and supplications",
      descriptionAr: "أذكار الصباح والدعوات"
    },
    azkar: [
      {
        id: "1",
        title: "Ayat al-Kursi",
        titleAr: "آية الكرسي",
        arabicText: "أَعُوذُ بِاللهِ مِنْ الشَّيْطَانِ الرَّجِيمِ اللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ",
        translation: "I seek refuge in Allah from Satan, the accursed. Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.",
        reference: "Al-Baqarah 2:255",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "2",
        title: "Surah Al-Ikhlas",
        titleAr: "سورة الإخلاص",
        arabicText: "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ هُوَ ٱللَّهُ أَحَدٌ، ٱللَّهُ ٱلصَّمَدُ، لَمْ يَلِدْ وَلَمْ يُولَدْ، وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ",
        translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent.'",
        reference: "Al-Ikhlas 112:1-4",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "3",
        title: "Surah Al-Falaq",
        titleAr: "سورة الفلق",
        arabicText: "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ، مِن شَرِّ مَا خَلَقَ، وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ، وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ، وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
        translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'I seek refuge in the Lord of daybreak from the evil of that which He created and from the evil of darkness when it settles and from the evil of the blowers in knots and from the evil of an envier when he envies.'",
        reference: "Al-Falaq 113:1-5",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "4",
        title: "Surah An-Nas",
        titleAr: "سورة الناس",
        arabicText: "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ، مَلِكِ ٱلنَّاسِ، إِلَٰهِ ٱلنَّاسِ، مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ، ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ، مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
        translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer who whispers [evil] into the breasts of mankind from among the jinn and mankind.'",
        reference: "An-Nas 114:1-6",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "5",
        title: "Morning Du'a",
        titleAr: "دعاء الصباح",
        arabicText: "أَصْبَـحْنا وَأَصْبَحَ المُـلْكُ لله وَالحَمدُ لله ، لا إلهَ إلاّ اللّهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُـلكُ ولهُ الحَمْـد، وهُوَ على كلّ شَيءٍ قدير ، رَبِّ أسْـأَلُـكَ خَـيرَ ما في هـذا اليوم وَخَـيرَ ما بَعْـدَه ، وَأَعـوذُ بِكَ مِنْ شَـرِّ ما في هـذا اليوم وَشَرِّ ما بَعْـدَه، رَبِّ أَعـوذُبِكَ مِنَ الْكَسَـلِ وَسـوءِ الْكِـبَر ، رَبِّ أَعـوذُ بِكَ مِنْ عَـذابٍ في النّـارِ وَعَـذابٍ في القَـبْر",
        translation: "We have entered the morning and the morning belongs to Allah, and all praise is due to Allah. There is no god but Allah alone, with no partner. His is the dominion and His is the praise, and He is over all things competent. O Lord, I ask You for the good of this day and the good of what comes after it, and I seek refuge in You from the evil of this day and the evil of what comes after it. O Lord, I seek refuge in You from laziness and the evil of old age. O Lord, I seek refuge in You from punishment in the Fire and punishment in the grave.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "6",
        title: "Morning Repentance",
        titleAr: "التوبة الصباحية",
        arabicText: "اللّهـمَّ أَنْتَ رَبِّـي لا إلهَ إلاّ أَنْتَ ، خَلَقْتَنـي وَأَنا عَبْـدُك ، وَأَنا عَلـى عَهْـدِكَ وَوَعْـدِكَ ما اسْتَـطَعْـت ، أَعـوذُبِكَ مِنْ شَـرِّ ما صَنَـعْت ، أَبـوءُ لَـكَ بِنِعْـمَتِـكَ عَلَـيَّ وَأَبـوءُ بِذَنْـبي فَاغْفـِرْ لي فَإِنَّـهُ لا يَغْـفِرُ الذُّنـوبَ إِلاّ أَنْتَ",
        translation: "O Allah, You are my Lord, there is no god but You. You created me and I am Your servant, and I am faithful to my covenant and my promise to You as much as I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for indeed no one forgives sins except You.",
        reference: "Sahih Bukhari 6306",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "7",
        title: "Contentment with Islam",
        titleAr: "الرضا بالإسلام",
        arabicText: "رَضيـتُ بِاللهِ رَبَّـاً وَبِالإسْلامِ ديـناً وَبِمُحَـمَّدٍ صلى الله عليه وسلم نَبِيّـاً",
        translation: "I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (peace be upon him) as my Prophet.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "8",
        title: "Morning Testimony",
        titleAr: "الشهادة الصباحية",
        arabicText: "اللّهُـمَّ إِنِّـي أَصْبَـحْتُ أُشْـهِدُك ، وَأُشْـهِدُ حَمَلَـةَ عَـرْشِـك ، وَمَلَائِكَتَكَ ، وَجَمـيعَ خَلْـقِك ، أَنَّـكَ أَنْـتَ اللهُ لا إلهَ إلاّ أَنْـتَ وَحْـدَكَ لا شَريكَ لَـك ، وَأَنَّ ُ مُحَمّـداً عَبْـدُكَ وَرَسـولُـك",
        translation: "O Allah, I have entered the morning bearing witness to You, and bearing witness to the bearers of Your Throne, and Your angels, and all of Your creation, that You are Allah, there is no god but You alone, with no partner, and that Muhammad is Your servant and Your Messenger.",
        reference: "Sahih Muslim 2719",
        times: 4,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "9",
        title: "Gratitude for Blessings",
        titleAr: "شكر النعم",
        arabicText: "اللّهُـمَّ ما أَصْبَـحَ بي مِـنْ نِعْـمَةٍ أَو بِأَحَـدٍ مِـنْ خَلْـقِك ، فَمِـنْكَ وَحْـدَكَ لا شريكَ لَـك ، فَلَـكَ الْحَمْـدُ وَلَـكَ الشُّكْـر",
        translation: "O Allah, whatever blessing I have received this morning or any of Your creation has received, it is from You alone, with no partner. To You belongs all praise and to You belongs all gratitude.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "10",
        title: "Sufficiency in Allah",
        titleAr: "الاستغناء بالله",
        arabicText: "حَسْبِـيَ اللّهُ لا إلهَ إلاّ هُوَ عَلَـيهِ تَوَكَّـلتُ وَهُوَ رَبُّ العَرْشِ العَظـيم",
        translation: "Allah is sufficient for me. There is no god but He. In Him I trust and He is the Lord of the Great Throne.",
        reference: "Sahih Muslim 2719",
        times: 7,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "11",
        title: "Protection by Allah's Name",
        titleAr: "الاستعاذة باسم الله",
        arabicText: "بِسـمِ اللهِ الذي لا يَضُـرُّ مَعَ اسمِـهِ شَيءٌ في الأرْضِ وَلا في السّمـاءِ وَهـوَ السّمـيعُ العَلـيم",
        translation: "In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, the All-Knowing.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "12",
        title: "Morning and Evening Remembrance",
        titleAr: "ذكر الصباح والمساء",
        arabicText: "اللّهُـمَّ بِكَ أَصْـبَحْنا وَبِكَ أَمْسَـينا ، وَبِكَ نَحْـيا وَبِكَ نَمُـوتُ وَإِلَـيْكَ النُّـشُور",
        translation: "O Allah, by You we enter the morning and by You we enter the evening, and by You we live and by You we die, and to You is the resurrection.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "13",
        title: "Morning Faith Declaration",
        titleAr: "إعلان الإيمان الصباحي",
        arabicText: "أَصْبَـحْـنا عَلَى فِطْرَةِ الإسْلاَمِ، وَعَلَى كَلِمَةِ الإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إبْرَاهِيمَ حَنِيفاً مُسْلِماً وَمَا كَانَ مِنَ المُشْرِكِينَ",
        translation: "We have entered the morning upon the natural disposition of Islam, and upon the word of sincerity, and upon the religion of our Prophet Muhammad (peace be upon him), and upon the religion of our father Ibrahim, inclining toward truth, and he was not of those who associate others with Allah.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "14",
        title: "Glory and Praise",
        titleAr: "التسبيح والحمد",
        arabicText: "سُبْحـانَ اللهِ وَبِحَمْـدِهِ عَدَدَ خَلْـقِه ، وَرِضـا نَفْسِـه ، وَزِنَـةَ عَـرْشِـه ، وَمِـدادَ كَلِمـاتِـه",
        translation: "Glory be to Allah and praise be to Him by the number of His creation, and by His pleasure, and by the weight of His Throne, and by the ink of His words.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "15",
        title: "Health Supplication",
        titleAr: "دعاء الصحة",
        arabicText: "اللّهُـمَّ عافِـني في بَدَنـي ، اللّهُـمَّ عافِـني في سَمْـعي ، اللّهُـمَّ عافِـني في بَصَـري ، لا إلهَ إلاّ أَنْـتَ",
        translation: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. There is no god but You.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "16",
        title: "Protection from Disbelief and Poverty",
        titleAr: "الاستعاذة من الكفر والفقر",
        arabicText: "اللّهُـمَّ إِنّـي أَعـوذُ بِكَ مِنَ الْكُـفر ، وَالفَـقْر ، وَأَعـوذُ بِكَ مِنْ عَذابِ القَـبْر ، لا إلهَ إلاّ أَنْـتَ",
        translation: "O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave. There is no god but You.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "17",
        title: "Comprehensive Protection",
        titleAr: "الاستعاذة الشاملة",
        arabicText: "اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في الدُّنْـيا وَالآخِـرَة ، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في ديني وَدُنْـيايَ وَأهْـلي وَمالـي ، اللّهُـمَّ اسْتُـرْ عـوْراتي وَآمِـنْ رَوْعاتـي ، اللّهُـمَّ احْفَظْـني مِن بَـينِ يَدَيَّ وَمِن خَلْفـي وَعَن يَمـيني وَعَن شِمـالي ، وَمِن فَوْقـي ، وَأَعـوذُ بِعَظَمَـتِكَ أَن أُغْـتالَ مِن تَحْتـي",
        translation: "O Allah, I ask You for pardon and well-being in this world and the next. O Allah, I ask You for pardon and well-being in my religion, my worldly affairs, my family and my wealth. O Allah, conceal my faults and calm my fears. O Allah, protect me from in front of me and from behind me, from my right and from my left, and from above me, and I seek refuge in Your greatness from being struck from beneath me.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "18",
        title: "Living and Self-Sustaining",
        titleAr: "الحي القيوم",
        arabicText: "يَا حَيُّ يَا قيُّومُ بِرَحْمَتِكَ أسْتَغِيثُ أصْلِحْ لِي شَأنِي كُلَّهُ وَلاَ تَكِلْنِي إلَى نَفْسِي طَـرْفَةَ عَيْنٍ",
        translation: "O Living, O Self-Sustaining, by Your mercy I seek help. Set right all my affairs and do not leave me to myself even for the blink of an eye.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "19",
        title: "Morning Blessing",
        titleAr: "دعاء بركة الصباح",
        arabicText: "أَصْبَـحْـنا وَأَصْبَـحْ المُـلكُ للهِ رَبِّ العـالَمـين ، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ خَـيْرَ هـذا الـيَوْم ، فَـتْحَهُ ، وَنَصْـرَهُ ، وَنـورَهُ وَبَـرَكَتَـهُ ، وَهُـداهُ ، وَأَعـوذُ بِـكَ مِـنْ شَـرِّ ما فـيهِ وَشَـرِّ ما بَعْـدَه",
        translation: "We have entered the morning and the morning belongs to Allah, Lord of the worlds. O Allah, I ask You for the good of this day, its opening, its victory, its light, its blessing, and its guidance, and I seek refuge in You from the evil of what is in it and the evil of what comes after it.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "20",
        title: "Knowledge of the Unseen",
        titleAr: "علم الغيب",
        arabicText: "اللّهُـمَّ عالِـمَ الغَـيْبِ وَالشّـهادَةِ فاطِـرَ السّماواتِ وَالأرْضِ رَبَّ كـلِّ شَـيءٍ وَمَليـكَه ، أَشْهَـدُ أَنْ لا إِلـهَ إِلاّ أَنْت ، أَعـوذُ بِكَ مِن شَـرِّ نَفْسـي وَمِن شَـرِّ الشَّيْـطانِ وَشِرْكِهِ ، وَأَنْ أَقْتَـرِفَ عَلـى نَفْسـي سوءاً أَوْ أَجُـرَّهُ إِلـى مُسْـلِم",
        translation: "O Allah, Knower of the unseen and the seen, Creator of the heavens and the earth, Lord of everything and its King, I bear witness that there is no god but You. I seek refuge in You from the evil of myself and from the evil of Satan and his associates, and from committing any wrongdoing against myself or bringing it upon a Muslim.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "21",
        title: "Allah's Perfect Words",
        titleAr: "كلمات الله التامات",
        arabicText: "أَعـوذُ بِكَلِمـاتِ اللّهِ التّـامّـاتِ مِنْ شَـرِّ ما خَلَـق",
        translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "22",
        title: "Blessings on the Prophet",
        titleAr: "الصلاة على النبي",
        arabicText: "اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ على نَبِيِّنَا مُحمَّد",
        translation: "O Allah, send blessings, peace, and mercy upon our Prophet Muhammad.",
        reference: "Sahih Muslim 2719",
        times: 10,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "23",
        title: "Protection from Hidden Shirk",
        titleAr: "الاستعاذة من الشرك الخفي",
        arabicText: "اللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ أَنْ نُشْرِكَ بِكَ شَيْئًا نَعْلَمُهُ ، وَنَسْتَغْفِرُكَ لِمَا لَا نَعْلَمُهُ",
        translation: "O Allah, we seek refuge in You from knowingly associating anything with You, and we seek Your forgiveness for what we do not know.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "24",
        title: "Protection from Worry and Sorrow",
        titleAr: "الاستعاذة من الهم والحزن",
        arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنْ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنْ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ، وَقَهْرِ الرِّجَالِ",
        translation: "O Allah, I seek refuge in You from worry and grief, and I seek refuge in You from incapacity and laziness, and I seek refuge in You from cowardice and miserliness, and I seek refuge in You from being overcome by debt and from being overpowered by men.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "25",
        title: "Seeking Forgiveness",
        titleAr: "الاستغفار",
        arabicText: "أسْتَغْفِرُ اللهَ العَظِيمَ الَّذِي لاَ إلَهَ إلاَّ هُوَ، الحَيُّ القَيُّومُ، وَأتُوبُ إلَيهِ",
        translation: "I seek forgiveness from Allah, the Most Great, there is no god but He, the Living, the Self-Sustaining, and I repent to Him.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "26",
        title: "Praise for Allah's Majesty",
        titleAr: "حمد جلال الله",
        arabicText: "يَا رَبِّ , لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ , وَلِعَظِيمِ سُلْطَانِكَ",
        translation: "O Lord, to You belongs all praise as befits the majesty of Your face and the greatness of Your sovereignty.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "27",
        title: "Seeking Beneficial Knowledge",
        titleAr: "طلب العلم النافع",
        arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلًا مُتَقَبَّلًا",
        translation: "O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "28",
        title: "Comprehensive Trust in Allah",
        titleAr: "التوكل الشامل على الله",
        arabicText: "اللَّهُمَّ أَنْتَ رَبِّي لا إِلَهَ إِلا أَنْتَ ، عَلَيْكَ تَوَكَّلْتُ ، وَأَنْتَ رَبُّ الْعَرْشِ الْعَظِيمِ , مَا شَاءَ اللَّهُ كَانَ ، وَمَا لَمْ يَشَأْ لَمْ يَكُنْ ، وَلا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ , أَعْلَمُ أَنَّ اللَّهَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ ، وَأَنَّ اللَّهَ قَدْ أَحَاطَ بِكُلِّ شَيْءٍ عِلْمًا , اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي ، وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا ، إِنَّ رَبِّي عَلَى صِرَاطٍ مُسْتَقِيمٍ",
        translation: "O Allah, You are my Lord, there is no god but You. In You I trust, and You are the Lord of the Great Throne. Whatever Allah wills happens, and whatever He does not will does not happen. There is no power and no strength except with Allah, the Most High, the Most Great. I know that Allah is capable of all things, and that Allah encompasses all things in knowledge. O Allah, I seek refuge in You from the evil of myself, and from the evil of every creature that You grasp by the forelock. Indeed, my Lord is on a straight path.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "29",
        title: "Declaration of Oneness",
        titleAr: "إعلان الوحدانية",
        arabicText: "لَا إلَه إلّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءِ قَدِيرِ",
        translation: "There is no god but Allah alone, with no partner. His is the dominion and His is the praise, and He is capable of all things.",
        reference: "Sahih Muslim 2719",
        times: 100,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "30",
        title: "Glory and Praise to Allah",
        titleAr: "سبحان الله وبحمده",
        arabicText: "سُبْحـانَ اللهِ وَبِحَمْـدِهِ",
        translation: "Glory be to Allah and praise be to Him.",
        reference: "Sahih Muslim 2719",
        times: 100,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "31",
        title: "Seeking Forgiveness and Repentance",
        titleAr: "الاستغفار والتوبة",
        arabicText: "أسْتَغْفِرُ اللهَ وَأتُوبُ إلَيْهِ",
        translation: "I seek forgiveness from Allah and I repent to Him.",
        reference: "Sahih Muslim 2719",
        times: 100,
        categoryId: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      }
    ]
  },
  evening: {
    category: {
      id: "2",
      name: "Evening",
      nameAr: "أذكار المساء",
      description: "Evening remembrance and supplications",
      descriptionAr: "أذكار المساء والدعوات"
    },
    azkar: [
      {
        id: "100",
        title: "Ayat al-Kursi",
        titleAr: "آية الكرسي",
        arabicText: "أَعُوذُ بِاللهِ مِنْ الشَّيْطَانِ الرَّجِيمِ اللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ",
        translation: "I seek refuge in Allah from Satan, the accursed. Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.",
        reference: "Al-Baqarah 2:255",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "101",
        title: "Last Two Verses of Al-Baqarah",
        titleAr: "آخر آيتين من سورة البقرة",
        arabicText: "أَعُوذُ بِاللهِ مِنْ الشَّيْطَانِ الرَّجِيمِ آمَنَ الرَّسُولُ بِمَا أُنْزِلَ إِلَيْهِ مِنْ رَبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ لَا نُفَرِّقُ بَيْنَ أَحَدٍ مِنْ رُسُلِهِ ۚ وَقَالُوا سَمِعْنَا وَأَطَعْنَا ۖ غُفْرَانَكَ رَبَّنَا وَإِلَيْكَ الْمَصِيرُ. لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَّسِينَآ أَوْ أَخْطَأْنَا رَبَّنَا وَلَا تَحْمِلْ عَلَيْنَا إِصْرًا كَمَا حَمَلْتَهُ عَلَى الَّذِينَ مِنْ قَبْلِنَا رَبَّنَا وَلَا تُحَمِّلْنَا مَا لَا طَاقَةَ لَنَا بِهِ وَاعْفُ عَنَّا وَاغْفِرْ لَنَا وَارْحَمْنَا أَنْتَ مَوْلَانَا فَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ",
        translation: "I seek refuge in Allah from Satan, the accursed. The Messenger has believed in what was revealed to him from his Lord, and [so have] the believers. All of them have believed in Allah and His angels and His books and His messengers, [saying], 'We make no distinction between any of His messengers.' And they say, 'We hear and we obey. [We seek] Your forgiveness, our Lord, and to You is the [final] destination.' Allah does not charge a soul except [with that within] its capacity. It will have [the consequence of] what [good] it has gained, and it will bear [the consequence of] what [evil] it has earned. 'Our Lord, do not impose blame upon us if we have forgotten or erred. Our Lord, and lay not upon us a burden like that which You laid upon those before us. Our Lord, and burden us not with that which we have no ability to bear. And pardon us; and forgive us; and have mercy upon us. You are our protector, so give us victory over the disbelieving people.'",
        reference: "Al-Baqarah 2:285-286",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "102",
        title: "Surah Al-Ikhlas",
        titleAr: "سورة الإخلاص",
        arabicText: "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ هُوَ ٱللَّهُ أَحَدٌ، ٱللَّهُ ٱلصَّمَدُ، لَمْ يَلِدْ وَلَمْ يُولَدْ، وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ",
        translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent.'",
        reference: "Al-Ikhlas 112:1-4",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "103",
        title: "Surah Al-Falaq",
        titleAr: "سورة الفلق",
        arabicText: "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ، مِن شَرِّ مَا خَلَقَ، وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ، وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ، وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
        translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'I seek refuge in the Lord of daybreak from the evil of that which He created and from the evil of darkness when it settles and from the evil of the blowers in knots and from the evil of an envier when he envies.'",
        reference: "Al-Falaq 113:1-5",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "104",
        title: "Surah An-Nas",
        titleAr: "سورة الناس",
        arabicText: "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ، مَلِكِ ٱلنَّاسِ، إِلَٰهِ ٱلنَّاسِ، مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ، ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ، مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
        translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer who whispers [evil] into the breasts of mankind from among the jinn and mankind.'",
        reference: "An-Nas 114:1-6",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "105",
        title: "Evening Du'a",
        titleAr: "دعاء المساء",
        arabicText: "أَمْسَيْـنا وَأَمْسـى المـلكُ لله وَالحَمدُ لله ، لا إلهَ إلاّ اللّهُ وَحدَهُ لا شَريكَ لهُ، لهُ المُـلكُ ولهُ الحَمْـد، وهُوَ على كلّ شَيءٍ قدير ، رَبِّ أسْـأَلُـكَ خَـيرَ ما في هـذهِ اللَّـيْلَةِ وَخَـيرَ ما بَعْـدَهـا ، وَأَعـوذُ بِكَ مِنْ شَـرِّ ما في هـذهِ اللَّـيْلةِ وَشَرِّ ما بَعْـدَهـا ، رَبِّ أَعـوذُبِكَ مِنَ الْكَسَـلِ وَسـوءِ الْكِـبَر ، رَبِّ أَعـوذُ بِكَ مِنْ عَـذابٍ في النّـارِ وَعَـذابٍ في القَـبْر",
        translation: "We have entered the evening and the evening belongs to Allah, and all praise is due to Allah. There is no god but Allah alone, with no partner. His is the dominion and His is the praise, and He is over all things competent. O Lord, I ask You for the good of this night and the good of what comes after it, and I seek refuge in You from the evil of this night and the evil of what comes after it. O Lord, I seek refuge in You from laziness and the evil of old age. O Lord, I seek refuge in You from punishment in the Fire and punishment in the grave.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "106",
        title: "Evening Repentance",
        titleAr: "التوبة المسائية",
        arabicText: "اللّهـمَّ أَنْتَ رَبِّـي لا إلهَ إلاّ أَنْتَ ، خَلَقْتَنـي وَأَنا عَبْـدُك ، وَأَنا عَلـى عَهْـدِكَ وَوَعْـدِكَ ما اسْتَـطَعْـت ، أَعـوذُبِكَ مِنْ شَـرِّ ما صَنَـعْت ، أَبـوءُ لَـكَ بِنِعْـمَتِـكَ عَلَـيَّ وَأَبـوءُ بِذَنْـبي فَاغْفـِرْ لي فَإِنَّـهُ لا يَغْـفِرُ الذُّنـوبَ إِلاّ أَنْتَ",
        translation: "O Allah, You are my Lord, there is no god but You. You created me and I am Your servant, and I am faithful to my covenant and my promise to You as much as I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for indeed no one forgives sins except You.",
        reference: "Sahih Bukhari 6306",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "107",
        title: "Contentment with Islam",
        titleAr: "الرضا بالإسلام",
        arabicText: "رَضيـتُ بِاللهِ رَبَّـاً وَبِالإسْلامِ ديـناً وَبِمُحَـمَّدٍ صلى الله عليه وسلم نَبِيّـاً",
        translation: "I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (peace be upon him) as my Prophet.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "108",
        title: "Evening Testimony",
        titleAr: "الشهادة المسائية",
        arabicText: "اللّهُـمَّ إِنِّـي أَمسيتُ أُشْـهِدُك ، وَأُشْـهِدُ حَمَلَـةَ عَـرْشِـك ، وَمَلَائِكَتَكَ ، وَجَمـيعَ خَلْـقِك ، أَنَّـكَ أَنْـتَ اللهُ لا إلهَ إلاّ أَنْـتَ وَحْـدَكَ لا شَريكَ لَـك ، وَأَنَّ ُ مُحَمّـداً عَبْـدُكَ وَرَسـولُـك",
        translation: "O Allah, I have entered the evening bearing witness to You, and bearing witness to the bearers of Your Throne, and Your angels, and all of Your creation, that You are Allah, there is no god but You alone, with no partner, and that Muhammad is Your servant and Your Messenger.",
        reference: "Sahih Muslim 2719",
        times: 4,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "109",
        title: "Gratitude for Evening Blessings",
        titleAr: "شكر نعم المساء",
        arabicText: "اللّهُـمَّ ما أَمسى بي مِـنْ نِعْـمَةٍ أَو بِأَحَـدٍ مِـنْ خَلْـقِك ، فَمِـنْكَ وَحْـدَكَ لا شريكَ لَـك ، فَلَـكَ الْحَمْـدُ وَلَـكَ الشُّكْـر",
        translation: "O Allah, whatever blessing I have received this evening or any of Your creation has received, it is from You alone, with no partner. To You belongs all praise and to You belongs all gratitude.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "110",
        title: "Sufficiency in Allah",
        titleAr: "الاستغناء بالله",
        arabicText: "حَسْبِـيَ اللّهُ لا إلهَ إلاّ هُوَ عَلَـيهِ تَوَكَّـلتُ وَهُوَ رَبُّ العَرْشِ العَظـيم",
        translation: "Allah is sufficient for me. There is no god but He. In Him I trust and He is the Lord of the Great Throne.",
        reference: "Sahih Muslim 2719",
        times: 7,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "111",
        title: "Protection by Allah's Name",
        titleAr: "الاستعاذة باسم الله",
        arabicText: "بِسـمِ اللهِ الذي لا يَضُـرُّ مَعَ اسمِـهِ شَيءٌ في الأرْضِ وَلا في السّمـاءِ وَهـوَ السّمـيعُ العَلـيم",
        translation: "In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, the All-Knowing.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "112",
        title: "Evening and Morning Remembrance",
        titleAr: "ذكر المساء والصباح",
        arabicText: "اللّهُـمَّ بِكَ أَمْسَـينا وَبِكَ أَصْـبَحْنا، وَبِكَ نَحْـيا وَبِكَ نَمُـوتُ وَإِلَـيْكَ الْمَصِيرُ",
        translation: "O Allah, by You we enter the evening and by You we enter the morning, and by You we live and by You we die, and to You is the destination.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "113",
        title: "Evening Faith Declaration",
        titleAr: "إعلان الإيمان المسائي",
        arabicText: "أَمْسَيْنَا عَلَى فِطْرَةِ الإسْلاَمِ، وَعَلَى كَلِمَةِ الإِخْلاَصِ، وَعَلَى دِينِ نَبِيِّنَا مُحَمَّدٍ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ، وَعَلَى مِلَّةِ أَبِينَا إبْرَاهِيمَ حَنِيفاً مُسْلِماً وَمَا كَانَ مِنَ المُشْرِكِينَ",
        translation: "We have entered the evening upon the natural disposition of Islam, and upon the word of sincerity, and upon the religion of our Prophet Muhammad (peace be upon him), and upon the religion of our father Ibrahim, inclining toward truth, and he was not of those who associate others with Allah.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "114",
        title: "Glory and Praise",
        titleAr: "التسبيح والحمد",
        arabicText: "سُبْحـانَ اللهِ وَبِحَمْـدِهِ عَدَدَ خَلْـقِه ، وَرِضـا نَفْسِـه ، وَزِنَـةَ عَـرْشِـه ، وَمِـدادَ كَلِمـاتِـه",
        translation: "Glory be to Allah and praise be to Him by the number of His creation, and by His pleasure, and by the weight of His Throne, and by the ink of His words.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "115",
        title: "Health Supplication",
        titleAr: "دعاء الصحة",
        arabicText: "اللّهُـمَّ عافِـني في بَدَنـي ، اللّهُـمَّ عافِـني في سَمْـعي ، اللّهُـمَّ عافِـني في بَصَـري ، لا إلهَ إلاّ أَنْـتَ",
        translation: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. There is no god but You.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "116",
        title: "Protection from Disbelief and Poverty",
        titleAr: "الاستعاذة من الكفر والفقر",
        arabicText: "اللّهُـمَّ إِنّـي أَعـوذُ بِكَ مِنَ الْكُـفر ، وَالفَـقْر ، وَأَعـوذُ بِكَ مِنْ عَذابِ القَـبْر ، لا إلهَ إلاّ أَنْـتَ",
        translation: "O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave. There is no god but You.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "117",
        title: "Comprehensive Protection",
        titleAr: "الاستعاذة الشاملة",
        arabicText: "اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في الدُّنْـيا وَالآخِـرَة ، اللّهُـمَّ إِنِّـي أسْـأَلُـكَ العَـفْوَ وَالعـافِـيةَ في ديني وَدُنْـيايَ وَأهْـلي وَمالـي ، اللّهُـمَّ اسْتُـرْ عـوْراتي وَآمِـنْ رَوْعاتـي ، اللّهُـمَّ احْفَظْـني مِن بَـينِ يَدَيَّ وَمِن خَلْفـي وَعَن يَمـيني وَعَن شِمـالي ، وَمِن فَوْقـي ، وَأَعـوذُ بِعَظَمَـتِكَ أَن أُغْـتالَ مِن تَحْتـي",
        translation: "O Allah, I ask You for pardon and well-being in this world and the next. O Allah, I ask You for pardon and well-being in my religion, my worldly affairs, my family and my wealth. O Allah, conceal my faults and calm my fears. O Allah, protect me from in front of me and from behind me, from my right and from my left, and from above me, and I seek refuge in Your greatness from being struck from beneath me.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "118",
        title: "Living and Self-Sustaining",
        titleAr: "الحي القيوم",
        arabicText: "يَا حَيُّ يَا قيُّومُ بِرَحْمَتِكَ أسْتَغِيثُ أصْلِحْ لِي شَأنِي كُلَّهُ وَلاَ تَكِلْنِي إلَى نَفْسِي طَـرْفَةَ عَيْنٍ",
        translation: "O Living, O Self-Sustaining, by Your mercy I seek help. Set right all my affairs and do not leave me to myself even for the blink of an eye.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "119",
        title: "Evening Blessing",
        titleAr: "دعاء بركة المساء",
        arabicText: "أَمْسَيْنا وَأَمْسَى الْمُلْكُ للهِ رَبِّ الْعَالَمَيْنِ، اللَّهُمَّ إِنَّي أسْأَلُكَ خَيْرَ هَذَه اللَّيْلَةِ فَتْحَهَا ونَصْرَهَا، ونُوْرَهَا وبَرَكَتهَا، وَهُدَاهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فيهِا وَشَرَّ مَا بَعْدَهَا",
        translation: "We have entered the evening and the evening belongs to Allah, Lord of the worlds. O Allah, I ask You for the good of this night, its opening, its victory, its light, its blessing, and its guidance, and I seek refuge in You from the evil of what is in it and the evil of what comes after it.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "120",
        title: "Knowledge of the Unseen",
        titleAr: "علم الغيب",
        arabicText: "اللّهُـمَّ عالِـمَ الغَـيْبِ وَالشّـهادَةِ فاطِـرَ السّماواتِ وَالأرْضِ رَبَّ كـلِّ شَـيءٍ وَمَليـكَه ، أَشْهَـدُ أَنْ لا إِلـهَ إِلاّ أَنْت ، أَعـوذُ بِكَ مِن شَـرِّ نَفْسـي وَمِن شَـرِّ الشَّيْـطانِ وَشِرْكِهِ ، وَأَنْ أَقْتَـرِفَ عَلـى نَفْسـي سوءاً أَوْ أَجُـرَّهُ إِلـى مُسْـلِم",
        translation: "O Allah, Knower of the unseen and the seen, Creator of the heavens and the earth, Lord of everything and its King, I bear witness that there is no god but You. I seek refuge in You from the evil of myself and from the evil of Satan and his associates, and from committing any wrongdoing against myself or bringing it upon a Muslim.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "121",
        title: "Allah's Perfect Words",
        titleAr: "كلمات الله التامات",
        arabicText: "أَعـوذُ بِكَلِمـاتِ اللّهِ التّـامّـاتِ مِنْ شَـرِّ ما خَلَـق",
        translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "122",
        title: "Blessings on the Prophet",
        titleAr: "الصلاة على النبي",
        arabicText: "اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ على نَبِيِّنَا مُحمَّد",
        translation: "O Allah, send blessings, peace, and mercy upon our Prophet Muhammad.",
        reference: "Sahih Muslim 2719",
        times: 10,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "123",
        title: "Protection from Hidden Shirk",
        titleAr: "الاستعاذة من الشرك الخفي",
        arabicText: "اللَّهُمَّ إِنَّا نَعُوذُ بِكَ مِنْ أَنْ نُشْرِكَ بِكَ شَيْئًا نَعْلَمُهُ ، وَنَسْتَغْفِرُكَ لِمَا لَا نَعْلَمُهُ",
        translation: "O Allah, we seek refuge in You from knowingly associating anything with You, and we seek Your forgiveness for what we do not know.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "124",
        title: "Protection from Worry and Sorrow",
        titleAr: "الاستعاذة من الهم والحزن",
        arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنْ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنْ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ، وَقَهْرِ الرِّجَالِ",
        translation: "O Allah, I seek refuge in You from worry and grief, and I seek refuge in You from incapacity and laziness, and I seek refuge in You from cowardice and miserliness, and I seek refuge in You from being overcome by debt and from being overpowered by men.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "125",
        title: "Seeking Forgiveness",
        titleAr: "الاستغفار",
        arabicText: "أسْتَغْفِرُ اللهَ العَظِيمَ الَّذِي لاَ إلَهَ إلاَّ هُوَ، الحَيُّ القَيُّومُ، وَأتُوبُ إلَيهِ",
        translation: "I seek forgiveness from Allah, the Most Great, there is no god but He, the Living, the Self-Sustaining, and I repent to Him.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "126",
        title: "Praise for Allah's Majesty",
        titleAr: "حمد جلال الله",
        arabicText: "يَا رَبِّ , لَكَ الْحَمْدُ كَمَا يَنْبَغِي لِجَلَالِ وَجْهِكَ , وَلِعَظِيمِ سُلْطَانِكَ",
        translation: "O Lord, to You belongs all praise as befits the majesty of Your face and the greatness of Your sovereignty.",
        reference: "Sahih Muslim 2719",
        times: 3,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "127",
        title: "Declaration of Oneness",
        titleAr: "إعلان الوحدانية",
        arabicText: "لَا إلَه إلّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءِ قَدِيرِ",
        translation: "There is no god but Allah alone, with no partner. His is the dominion and His is the praise, and He is capable of all things.",
        reference: "Sahih Muslim 2719",
        times: 100,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "128",
        title: "Comprehensive Trust in Allah",
        titleAr: "التوكل الشامل على الله",
        arabicText: "اللَّهُمَّ أَنْتَ رَبِّي لا إِلَهَ إِلا أَنْتَ ، عَلَيْكَ تَوَكَّلْتُ ، وَأَنْتَ رَبُّ الْعَرْشِ الْعَظِيمِ , مَا شَاءَ اللَّهُ كَانَ ، وَمَا لَمْ يَشَأْ لَمْ يَكُنْ ، وَلا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ , أَعْلَمُ أَنَّ اللَّهَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ ، وَأَنَّ اللَّهَ قَدْ أَحَاطَ بِكُلِّ شَيْءٍ عِلْمًا , اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي ، وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا ، إِنَّ رَبِّي عَلَى صِرَاطٍ مُسْتَقِيمٍ",
        translation: "O Allah, You are my Lord, there is no god but You. In You I trust, and You are the Lord of the Great Throne. Whatever Allah wills happens, and whatever He does not will does not happen. There is no power and no strength except with Allah, the Most High, the Most Great. I know that Allah is capable of all things, and that Allah encompasses all things in knowledge. O Allah, I seek refuge in You from the evil of myself, and from the evil of every creature that You grasp by the forelock. Indeed, my Lord is on a straight path.",
        reference: "Sahih Muslim 2719",
        times: 1,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "129",
        title: "Glory and Praise to Allah",
        titleAr: "سبحان الله وبحمده",
        arabicText: "سُبْحـانَ اللهِ وَبِحَمْـدِهِ",
        translation: "Glory be to Allah and praise be to Him.",
        reference: "Sahih Muslim 2719",
        times: 100,
        categoryId: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      }
    ]
  },
  prayer: {
    category: {
      id: "3",
      name: "Prayer",
      nameAr: "أذكار الصلاة",
      description: "Remembrance during and after prayer",
      descriptionAr: "أذكار الصلاة وبعدها"
    },
    azkar: [
      {
        id: "200",
        title: "Seeking Forgiveness After Prayer",
        titleAr: "الاستغفار بعد الصلاة",
        arabicText: "أَسْـتَغْفِرُ الله، أَسْـتَغْفِرُ الله، أَسْـتَغْفِرُ الله",
        translation: "I seek forgiveness from Allah, I seek forgiveness from Allah, I seek forgiveness from Allah.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "201",
        title: "Peace and Blessings",
        titleAr: "السلام والبركات",
        arabicText: "اللّهُـمَّ أَنْـتَ السَّلامُ ، وَمِـنْكَ السَّلام ، تَبارَكْتَ يا ذا الجَـلالِ وَالإِكْـرام",
        translation: "O Allah, You are Peace, and from You comes peace. Blessed are You, O Possessor of majesty and honor.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "202",
        title: "Declaration of Oneness After Prayer",
        titleAr: "إعلان الوحدانية بعد الصلاة",
        arabicText: "لا إلهَ إلاّ اللّهُ وحدَهُ لا شريكَ لهُ، لهُ المُـلْكُ ولهُ الحَمْد، وهوَ على كلّ شَيءٍ قَدير، اللّهُـمَّ لا مانِعَ لِما أَعْطَـيْت، وَلا مُعْطِـيَ لِما مَنَـعْت، وَلا يَنْفَـعُ ذا الجَـدِّ مِنْـكَ الجَـد",
        translation: "There is no god but Allah alone, with no partner. His is the dominion and His is the praise, and He is capable of all things. O Allah, there is none who can withhold what You give, and none who can give what You withhold, and the wealth of the wealthy cannot benefit them from You.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "203",
        title: "Comprehensive Declaration",
        titleAr: "الإعلان الشامل",
        arabicText: "لا إلهَ إلاّ اللّه, وحدَهُ لا شريكَ لهُ، لهُ الملكُ ولهُ الحَمد، وهوَ على كلّ شيءٍ قدير، لا حَـوْلَ وَلا قـوَّةَ إِلاّ بِاللهِ، لا إلهَ إلاّ اللّـه، وَلا نَعْـبُـدُ إِلاّ إيّـاه, لَهُ النِّعْـمَةُ وَلَهُ الفَضْل وَلَهُ الثَّـناءُ الحَـسَن، لا إلهَ إلاّ اللّهُ مخْلِصـينَ لَـهُ الدِّينَ وَلَوْ كَـرِهَ الكـافِرون",
        translation: "There is no god but Allah alone, with no partner. His is the dominion and His is the praise, and He is capable of all things. There is no power and no strength except with Allah. There is no god but Allah, and we worship none but Him. To Him belongs the favor and to Him belongs the excellence and to Him belongs the good praise. There is no god but Allah, sincerely devoted to Him in religion, even if the disbelievers dislike it.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "204",
        title: "Prayer Tasbih",
        titleAr: "تسبيح الصلاة",
        arabicText: "سُـبْحانَ اللهِ، والحَمْـدُ لله ، واللهُ أكْـبَر",
        translation: "Glory be to Allah, and praise be to Allah, and Allah is the Greatest.",
        reference: "Sahih Muslim 2691",
        times: 33,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "205",
        title: "Declaration of Oneness",
        titleAr: "إعلان الوحدانية",
        arabicText: "لا إلهَ إلاّ اللّهُ وَحْـدَهُ لا شريكَ لهُ، لهُ الملكُ ولهُ الحَمْد، وهُوَ على كُلّ شَيءٍ قَـدير",
        translation: "There is no god but Allah alone, with no partner. His is the dominion and His is the praise, and He is capable of all things.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "206",
        title: "The Three Quls",
        titleAr: "المعوذات الثلاث",
        arabicText: "بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ هُوَ ٱللَّهُ أَحَدٌ، ٱللَّهُ ٱلصَّمَدُ، لَمْ يَلِدْ وَلَمْ يُولَدْ، وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ. بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ، مِن شَرِّ مَا خَلَقَ، وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ، وَمِن شَرِّ ٱلنَّفَّٰثَٰتِ فِى ٱلْعُقَدِ، وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ. بِسْمِ اللهِ الرَّحْمنِ الرَّحِيم قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ، مَلِكِ ٱلنَّاسِ، إِلَٰهِ ٱلنَّاسِ، مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ، ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ، مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
        translation: "In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent.' In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'I seek refuge in the Lord of daybreak from the evil of that which He created and from the evil of darkness when it settles and from the evil of the blowers in knots and from the evil of an envier when he envies.' In the name of Allah, the Entirely Merciful, the Especially Merciful. Say, 'I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer who whispers [evil] into the breasts of mankind from among the jinn and mankind.'",
        reference: "Sahih Muslim 2691",
        times: 3,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "207",
        title: "Ayat al-Kursi",
        titleAr: "آية الكرسي",
        arabicText: "أَعُوذُ بِاللهِ مِنْ الشَّيْطَانِ الرَّجِيمِ اللّهُ لاَ إِلَـهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ لاَ تَأْخُذُهُ سِنَةٌ وَلاَ نَوْمٌ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الأَرْضِ مَن ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلاَّ بِإِذْنِهِ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ وَلاَ يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلاَّ بِمَا شَاء وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالأَرْضَ وَلاَ يَؤُودُهُ حِفْظُهُمَا وَهُوَ الْعَلِيُّ الْعَظِيمُ",
        translation: "I seek refuge in Allah from Satan, the accursed. Allah - there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.",
        reference: "Al-Baqarah 2:255",
        times: 1,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "208",
        title: "Declaration of Life and Death",
        titleAr: "إعلان الحياة والموت",
        arabicText: "لا إلهَ إلاّ اللّهُ وحْـدَهُ لا شريكَ لهُ، لهُ المُلكُ ولهُ الحَمْد، يُحيـي وَيُمـيتُ وهُوَ على كُلّ شيءٍ قدير",
        translation: "There is no god but Allah alone, with no partner. His is the dominion and His is the praise. He gives life and causes death, and He is capable of all things.",
        reference: "Sahih Muslim 2691",
        times: 10,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "209",
        title: "Seeking Beneficial Knowledge",
        titleAr: "طلب العلم النافع",
        arabicText: "اللّهُـمَّ إِنِّـي أَسْأَلُـكَ عِلْمـاً نافِعـاً وَرِزْقـاً طَيِّـباً ، وَعَمَـلاً مُتَقَـبَّلاً",
        translation: "O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "210",
        title: "Seeking Protection from Hell",
        titleAr: "الاستعاذة من النار",
        arabicText: "اللَّهُمَّ أَجِرْنِي مِنْ النَّار",
        translation: "O Allah, protect me from the Fire.",
        reference: "Sahih Muslim 2691",
        times: 7,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "211",
        title: "Seeking Help in Remembrance",
        titleAr: "طلب العون في الذكر",
        arabicText: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
        translation: "O Allah, help me to remember You, to thank You, and to worship You in the best way.",
        reference: "Sahih Muslim 2691",
        times: 1,
        categoryId: "3",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      }
    ]
  },
  general: {
    category: {
      id: "4",
      name: "General",
      nameAr: "أذكار عامة",
      description: "General remembrance and supplications",
      descriptionAr: "أذكار عامة ودعوات"
    },
    azkar: [
      {
        id: "300",
        title: "Wearing Clothes",
        titleAr: "دعاء لبس الثوب",
        arabicText: "الحمدُ للهِ الّذي كَساني هذا (الثّوب) وَرَزَقَنيه مِنْ غَـيـْرِ حَولٍ مِنّي وَلا قـوّة",
        translation: "Praise be to Allah who has clothed me with this (garment) and provided it for me without any power or strength from me",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "301",
        title: "Wearing New Clothes",
        titleAr: "دعاء لبس الثوب الجديد",
        arabicText: "اللهم لك الحمد أنت كسوتنيه، أسألك من خيره",
        translation: "O Allah, to You belongs all praise, You have clothed me with it. I ask You for its good.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "302",
        title: "Distress Du'a",
        titleAr: "دعاء الكرب",
        arabicText: "لا إله إلا الله العظيم الحليم، لا إله إلا الله رب العرش العظيم، لا إله إلا الله رب السماوات، ورب الأرض ورب العرش الكريم اللهم رحمتك أرجو فلا تكلني إلى نفسي طرفة عين وأصلح لي شأني كله ، لا إله إلا أنت لا إله إلا أنت سبحانك إني كنت من الظالمين الله الله رب لا أشرك به شيئا",
        translation: "There is no god but Allah, the Great, the Forbearing. There is no god but Allah, Lord of the Mighty Throne. There is no god but Allah, Lord of the heavens and Lord of the earth and Lord of the Noble Throne. O Allah, I hope for Your mercy, so do not leave me to myself for even the blink of an eye, and set right all my affairs. There is no god but You. There is no god but You. Glory be to You, I was indeed among the wrongdoers. Allah, Allah, my Lord, I do not associate anything with Him.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "303",
        title: "Du'a for Worry and Sorrow",
        titleAr: "دعاء الهم والحزن",
        arabicText: "اللهم إني عبدك ابن عبدك ابن أمتك ناصيتي بيدك ماض في حكمك ، عدل في قضاؤك أسألك بكل اسم هو لك سميت به نفسك أو أنزلته في كتابك ، أو علمته أحداً من خلقك أو استأثرت به في علم الغيب عندك أن تجعل القرآن ربيع قلبي ، ونور صدري وجلاء حزني وذهاب همي. اللهم إني أعوذ بك من الهم والحزن والعجز والكسل والبخل والجبن ، وضلع الدين وغلبة الرجال",
        translation: "O Allah, I am Your servant, son of Your servant, son of Your maidservant. My forelock is in Your hand, Your command over me is forever executed and Your decree over me is just. I ask You by every name belonging to You which You have named Yourself with, or revealed in Your Book, or You taught to any of Your creation, or You have preserved in the knowledge of the unseen with You, that You make the Quran the life of my heart and the light of my chest and the removal of my sadness and the departure of my distress. O Allah, I seek refuge in You from worry and grief, from incapacity and laziness, from cowardice and miserliness, from being overcome by debt and from being overpowered by men.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "304",
        title: "Du'a for Debt Relief",
        titleAr: "دعاء قضاء الدين",
        arabicText: "اللهم اكفنى بحلالك عن حرامك وأغننى بفضلك عمن سواك",
        translation: "O Allah, suffice me with what You have made lawful against what You have made unlawful, and make me independent of all others besides You by Your bounty.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "305",
        title: "Du'a for Wind",
        titleAr: "دعاء الريح",
        arabicText: "اللهم إنى أسألك خيرها، وخير ما فيها، وخير ما أرسلت به، وأعوذ بك من شرها، وشر ما فيها وشر ما أرسلت به",
        translation: "O Allah, I ask You for its good, and the good of what is in it, and the good of what You have sent it with, and I seek refuge in You from its evil, and the evil of what is in it and the evil of what You have sent it with.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "306",
        title: "Du'a for Thunder",
        titleAr: "دعاء الرعد",
        arabicText: "سبحان الله الذي يسبح الرعد بحمده والملائكة من خيفته",
        translation: "Glory be to Allah, whom the thunder glorifies with His praise, and the angels from fear of Him.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "307",
        title: "Du'a for Visiting Graves",
        titleAr: "دعاء زيارة القبور",
        arabicText: "السلام عليكم أهل الديار من المؤمنين والمسلمين، وإنا إن شاء الله بكم لاحقون ويرحم الله المستقدمين منا والمستأخرين، أسأل الله لنا ولكم العافية",
        translation: "Peace be upon you, O people of the dwellings, believers and Muslims. Indeed, we will join you, Allah willing, and may Allah have mercy on those who have gone ahead of us and those who come after us. I ask Allah for well-being for us and for you.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "308",
        title: "Du'a for Rain",
        titleAr: "دعاء نزول المطر",
        arabicText: "اللهم صيباَ نافعاَ",
        translation: "O Allah, make it a beneficial rain.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "309",
        title: "Du'a for Riding",
        titleAr: "دعاء ركوب الدابة",
        arabicText: "بسم الله ، الحمد لله ، سبحان الذي سخر لنا هذا وماكنا له مقرنين وإنا إلى ربنا لمنقلبون، الحمد لله ، الحمد لله ، الحمد لله ، الله اكبر ، الله أكبر ، الله أكبر ، سبحانك اللهم إني ظلمت نفسي فاغفر لي ، فإنه لايغفر الذنوب إلا أنت",
        translation: "In the name of Allah, praise be to Allah, glory be to Him who has subjected this to us, and we were not able to do it, and indeed, to our Lord we will return. Praise be to Allah, praise be to Allah, praise be to Allah. Allah is the Greatest, Allah is the Greatest, Allah is the Greatest. Glory be to You, O Allah, I have wronged myself, so forgive me, for indeed no one forgives sins except You.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "310",
        title: "Du'a for Travel",
        titleAr: "دعاء السفر",
        arabicText: "اللهم إنا نسألك في سفرنا هذا البر والتقوى، ومن العمل ماترضى ، اللهم هون علينا سفرنا هـذا واطوِ عنا بعده، اللهم أنت الصاحب في السفر، والخليفة في الأهل، اللهم إني أعوذ بك من وعثاء السفر وكآبة المنظر وسوء المنقلب في المال والأهل. وإذا رجع قالهن وزاد فيهن ـ آيبون ،تآئبون، عابدون ، لربنا حامدون",
        translation: "O Allah, we ask You in this journey of ours for righteousness and piety, and for deeds that are pleasing to You. O Allah, make this journey easy for us and make its distance short for us. O Allah, You are the companion in travel and the successor in the family. O Allah, I seek refuge in You from the hardships of travel, from having a changed mind and from having a bad return in wealth and family. And when he returns, he says them and adds to them: 'We are returning, repenting, worshipping, and praising our Lord.'",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "311",
        title: "Du'a for Traveler to Resident",
        titleAr: "دعاء المسافر للمقيم",
        arabicText: "استودعكم الله الذي لا تضيع ودائعه",
        translation: "I entrust you to Allah, who does not lose what is entrusted to Him.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "312",
        title: "Du'a for Resident to Traveler",
        titleAr: "دعاء المقيم للمسافر",
        arabicText: "أستودع ُ الله دينك وأمانتك ، وخواتيم عملك زودك الله التقوى، وغفر ذنبك، ويسر لك الخير حيث ما كنت",
        translation: "I entrust to Allah your religion, your trust, and the final outcome of your deeds. May Allah provide you with piety, forgive your sins, and make good easy for you wherever you are.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "313",
        title: "Du'a for Staying in a Place",
        titleAr: "دعاء النزول في مكان",
        arabicText: "أعوذ بكلمات الله التامات من شر ما خلق",
        translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "314",
        title: "Du'a Between Prostrations",
        titleAr: "الدعاء بين السجدتين",
        arabicText: "رب اغفر لي رب اغفر لي اللهم اغفر لي ، وارحمني واهدني واجبرني وعافني وارزقني وارفعني",
        translation: "Lord, forgive me, Lord, forgive me. O Allah, forgive me, have mercy on me, guide me, strengthen me, grant me health, provide for me, and raise me.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "315",
        title: "Du'a for Difficult Matters",
        titleAr: "دعاء من استصعب عليه أمر",
        arabicText: "اللهم لاسهل إلا ماجعلته سهلا وأنت تجعل الحزن إذا شئت سهلا",
        translation: "O Allah, there is nothing easy except what You make easy, and You make the difficult easy if You will.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "316",
        title: "Du'a for Protection from Shirk",
        titleAr: "دعاء الخوف من الشرك",
        arabicText: "اللهم إني أ عوذ بك أن أشرك بك وأنا أعلم ، وأستغفرك لما لا أعلم",
        translation: "O Allah, I seek refuge in You from associating anything with You knowingly, and I seek Your forgiveness for what I do not know.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "317",
        title: "What to Say in a Gathering",
        titleAr: "ما يقال في المجلس",
        arabicText: "رب اغفر لي وتب عليّ إنك أنت التواب الغفور",
        translation: "Lord, forgive me and accept my repentance, for You are the Accepter of Repentance, the Oft-Forgiving.",
        reference: "Sahih Muslim 2715",
        times: 100,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "318",
        title: "Expiation for Gathering",
        titleAr: "كفارة المجلس",
        arabicText: "سبحانك اللهم وبحمدك ، أشهد أن لا إله إلا أنت أستغفرك وأتوب إليك",
        translation: "Glory be to You, O Allah, and praise be to You. I bear witness that there is no god but You. I seek Your forgiveness and I repent to You.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "319",
        title: "Du'a for Seeing Afflicted Person",
        titleAr: "دعاء من رأى مبتلى",
        arabicText: "الحمد لله الذي عافاني مما ابتلا به وفضلني على كثير ممن خلق تفضيلاً",
        translation: "Praise be to Allah who has protected me from what He has afflicted him with and has favored me over many of His creation with great favor.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "320",
        title: "Du'a for Anger",
        titleAr: "دعاء الغضب",
        arabicText: "أعوذ بالله من الشيطان الرجيـم",
        translation: "I seek refuge in Allah from Satan, the accursed.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "321",
        title: "Du'a for Newlyweds",
        titleAr: "الدعاء للمتزوج",
        arabicText: "بارك الله لك ، وبارك عليك ، وجمع بينكما في خير",
        translation: "May Allah bless you and bestow His blessings upon you, and may He unite you in goodness.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "322",
        title: "Du'a for Newlywed for Himself",
        titleAr: "دعاء المتزوج لنفسه",
        arabicText: "اللهم إني أسألك خيرها وخير ماجبلتها عليه وأعوذ بك من شرها وشر ماجبلتها عليه ، وإذا اشترى بعيراً فليأخذ بذروة سنامه وليقل مثل ذلك",
        translation: "O Allah, I ask You for her good and the good of what You have created her for, and I seek refuge in You from her evil and the evil of what You have created her for. And if he buys a camel, let him take hold of the hump and say the same thing.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "323",
        title: "Du'a Before Intimacy",
        titleAr: "الدعاء قبل الجماع",
        arabicText: "بسم الله ـ اللهم جنبنا الشيطان، وجنب الشيطان مارزقتنا",
        translation: "In the name of Allah. O Allah, keep Satan away from us and keep Satan away from what You have provided us.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "324",
        title: "Du'a for Sneezing",
        titleAr: "دعاء العطاس",
        arabicText: "إذا عطـس أحـدكم فليقل : الحمـد لله ، وليقل له أخـوه ، أو صاحبه : يرحمـك الله فـإذا قال له : يرحمك الله ، فليقل : يهديكم الله ويصلح بالكم",
        translation: "When one of you sneezes, let him say: 'Praise be to Allah.' And let his brother or companion say to him: 'May Allah have mercy on you.' And when he says to him: 'May Allah have mercy on you,' let him say: 'May Allah guide you and set your affairs right.'",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "325",
        title: "Du'a for Breaking Fast",
        titleAr: "الدعاء عند افطار الصائم",
        arabicText: "ذهب الضمـأ ، وأبتلت العروق ، وثبت الأجر إن شاء الله",
        translation: "Thirst has gone, the veins are moistened, and the reward is confirmed, Allah willing.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "326",
        title: "Du'a for Breaking Fast at Someone's House",
        titleAr: "الدعاء إذا أفطر عند أهل بيت",
        arabicText: "أفطر عندكم الصائمون ، وأكل طعامكم الأبرار ، وصلت عليكم الملائكة",
        translation: "The fasting ones have broken their fast with you, the righteous have eaten your food, and the angels have sent blessings upon you.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "327",
        title: "Du'a for Seeing New Moon",
        titleAr: "دعاء رؤية الهلال",
        arabicText: "الله أكبر ، اللهم أهله علينا بالأمن ، والإيمان والسلامة ، والإسلام ، والتوفيق لما تحب وترضى ربنا وربك الله",
        translation: "Allah is the Greatest. O Allah, bring it upon us with security, faith, safety, Islam, and success in what You love and are pleased with. Our Lord and your Lord is Allah.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "328",
        title: "Du'a for Calamity",
        titleAr: "دعاء من أصيب بمصيبة",
        arabicText: "إنا لله وإنا إليه راجعون اللهم أجرني في مصيبتي واخلف لي خيرا منها",
        translation: "Indeed, to Allah we belong and indeed, to Him we will return. O Allah, reward me in my calamity and replace it for me with something better.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "329",
        title: "Du'a for Visiting the Sick",
        titleAr: "الدعاء للمريض في عيادته",
        arabicText: "لابأس طهور إن شاء الله مامن عبد مسلم يعود مريضاً لم يحضر أجله فيقول سبع مرات : أسأل الله العظيم رب العرش العظيم أن يشفيك إلا عوفي",
        translation: "No harm, it is a purification, Allah willing. There is no Muslim servant who visits a sick person whose time has not come and says seven times: 'I ask Allah the Great, Lord of the Mighty Throne, to heal you,' except that he is cured.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "330",
        title: "Du'a for Dying Person",
        titleAr: "دعاء المريض الذي يئس من حياته",
        arabicText: "اللهم اغفر لي وارحمني والحقني بالرفيق الأعلى",
        translation: "O Allah, forgive me, have mercy on me, and join me with the highest companion.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "331",
        title: "Du'a for Protecting Children",
        titleAr: "ما يعوذ به الأولاد",
        arabicText: "أعيذكما بكلمات الله التامة من كل شيطان وهامة ، ومن كل عين لامة",
        translation: "I seek refuge for both of you in the perfect words of Allah from every devil and poisonous creature, and from every evil eye.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "332",
        title: "Du'a for Meeting Enemy or Authority",
        titleAr: "دعاء لقاء العدو وذي السلطان",
        arabicText: "حسـبنا الله ونعـم الـوكـيل اللهم إنا نجعلك في نحورهم ونعوذ بك من شرورهم اللهم أنت عضدي ، وأنت نصيري ، بك أجول وبك أصول وبك أقاتل",
        translation: "Allah is sufficient for us and He is the best disposer of affairs. O Allah, we make You their adversary and we seek refuge in You from their evil. O Allah, You are my supporter and You are my helper. With You I advance and with You I retreat and with You I fight.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "333",
        title: "Du'a for Istikhara",
        titleAr: "دعاء صلاة الاستخارة",
        arabicText: "اللهم إني أستخيرك بعلمك ، وأستقدرك بقدرتك وأسألك من فضلك العظيم فإنك تقدر ولا أقدر وتعلم ولاأعلم وأنت علام الغيوب ، اللهم إن كنت تعلم أن هذا الأمر ـ ويسمي حاجته ـ خيرا لي في ديني ومعاشي وعاقبة أمري ـ أو قال عاجله وآجله ـ فأقدره لي ويسره لي ثم بارك لي فيه ، وإن كنت تعلم أن هذا الأمر شر لي في ديني ومعاشي وعاقبة أمري ـ أو قال عاجله وآجله ـ فاصرفه عني واصرفني عنه واقدر لي الخير حيث كان ثم ارضني به",
        translation: "O Allah, I seek Your guidance through Your knowledge, and I seek Your help through Your power, and I ask You from Your great bounty. For You have power and I have none, and You know and I know not, and You are the Knower of the unseen. O Allah, if You know that this matter (and he mentions his need) is good for me in my religion, my livelihood, and the outcome of my affairs (or he said: its immediate and future), then decree it for me, make it easy for me, and bless it for me. And if You know that this matter is evil for me in my religion, my livelihood, and the outcome of my affairs (or he said: its immediate and future), then turn it away from me and turn me away from it, and decree for me the good wherever it may be, and make me satisfied with it.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "334",
        title: "Du'a for Prostration of Recitation",
        titleAr: "دعاء سجود التلاوة",
        arabicText: "سجد وجهي للذي خلقه ،وشق سمعه وبصره بحوله وقوته ( فتبارك الله احسن الخالقين )",
        translation: "My face has prostrated to the One who created it, and brought forth its hearing and sight by His power and strength. (So blessed is Allah, the Best of creators.)",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "335",
        title: "Du'a for Opening Prayer",
        titleAr: "دعاء الاستفتاح",
        arabicText: "اللهم باعد بيني وبين خطاياي كما باعدت بين المشرق والغرب ، اللهم نقني من خطاياي كما ينقى الثوب الأبيض من الدنس، اللهم اغسلني من خطاياي بالثلج والماء والبرد. سبحانك اللهم وبحمدك وتبارك اسمك وتعالى جدُّك ولاإله غيرك. الله اكبر كبيرا ، الله اكبر كبيرا ، الله اكبر كبيرا ، والحمد لله كثيرا ، والحمد لله كثيرا ، والحمد لله كثيرا ، وسبحان الله بكرة وأصيلا(ثلاثـــا) ـ اعوذ بالله من الشيطان من نفحه ونفثه وهمزه",
        translation: "O Allah, distance me from my sins as You have distanced the East from the West. O Allah, purify me from my sins as a white garment is purified from filth. O Allah, wash me from my sins with snow, water, and hail. Glory be to You, O Allah, and praise be to You. Blessed is Your name and exalted is Your majesty, and there is no god but You. Allah is the Greatest, Allah is the Greatest, Allah is the Greatest. And praise be to Allah much, and praise be to Allah much, and praise be to Allah much. And glory be to Allah morning and evening (three times). I seek refuge in Allah from Satan from his puffing, his spitting, and his whisper.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "336",
        title: "Du'a for Entering Market",
        titleAr: "دعاء دخول السوق",
        arabicText: "لا إله إلا الله وحده لا شريك له، له الملك وله الحمد يحيي ويميت وهو حي لا يموت بيده الخير وهو على كل شيء قدير (كتب الله له ألف ألف حسنة ومحا عنه ألف ألف سيئة ورفع له ألف الف درجة وبنى له بيتا في الجنة). بسم الله، اللهم إني أسألك خير هذه السوق، وخير ما فيها، وأعوذ بك من شرها وشر ما فيها، اللهم إني أعوذ بك أن أصيب بها يميناً فاجرةً، أو صفقة خاسرة",
        translation: "There is no god but Allah alone, with no partner. His is the dominion and His is the praise. He gives life and causes death, and He is living and does not die. In His hand is all good, and He is capable of all things. (Allah writes for him a thousand thousand good deeds and erases from him a thousand thousand bad deeds and raises him a thousand thousand degrees and builds for him a house in Paradise.) In the name of Allah. O Allah, I ask You for the good of this market and the good of what is in it, and I seek refuge in You from its evil and the evil of what is in it. O Allah, I seek refuge in You from making a false oath or a losing transaction.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "337",
        title: "Du'a for Committing Sin",
        titleAr: "عند فعل الذنب أو ارتكاب المعصية",
        arabicText: "مامن عبد يذنب ذنباً فيتوضأ فيحسن الطهور،ثم يقوم فيصلي ركعتين ، ثم يستغفر الله لذلك الذنب إلاَّ غُفر له",
        translation: "There is no servant who commits a sin, then performs ablution and does it well, then stands and prays two rak'ahs, then seeks forgiveness from Allah for that sin, except that he is forgiven.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "338",
        title: "Du'a for Hearing Animal Sounds",
        titleAr: "الدعاء عند سماع أصوات الحيوانات",
        arabicText: "الدعاء عند صياح الديك : اللهم إني أسألك من فضلـــك. إذا سمعتم صياح الديك[من الليل]،فاسألوا الله من فَضْلِهِ فإنها رأت ملكاً و إذا سمعتم نهيق الحمار،فتعوَّذوا بالله من الشيطان فإنها رأت شَيْطَاناً. الدعاء عند صياح الديك و نهيق الحمار و نباح الكلاب: أعوذ بالله من الشيطان الرجيم. إذا سمعتم نُباحَ الكلاب و نهيق الحمير بالليل فتعوذوا بالله فإنهن يَرَيْنَ ما لا ترون",
        translation: "Du'a when hearing a rooster crow: 'O Allah, I ask You from Your bounty.' When you hear a rooster crow [at night], ask Allah from His bounty, for it has seen an angel. And when you hear a donkey bray, seek refuge in Allah from Satan, for it has seen a devil. Du'a when hearing a rooster crow, donkey bray, and dogs bark: 'I seek refuge in Allah from Satan, the accursed.' When you hear dogs barking and donkeys braying at night, seek refuge in Allah, for they see what you do not see.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "339",
        title: "Master of Seeking Forgiveness",
        titleAr: "سيد الاستغفار",
        arabicText: "اللهم أنت ربي لا إله إلا أنت ، خلقتني وأنا عبدك وأنا على عهدك ووعدك ما استطعت أعوذ بك من شر ما صنعت، أبوئ لك بنعمتك على وأبوئ بذنبي ، فاغفر لي فانه لا يغفر الذنوب إلا أنت",
        translation: "O Allah, You are my Lord, there is no god but You. You created me and I am Your servant, and I am faithful to my covenant and my promise to You as much as I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for indeed no one forgives sins except You.",
        reference: "Sahih Bukhari 6306",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "340",
        title: "Du'a for Body Pain",
        titleAr: "الدعاء إذا أحسست بوجع في جسدك",
        arabicText: "ضع يدك على الذي تألَّم من جسدك وقل: بسم الله ،ثلاثاً ،وقل سبع مرات: أعوذُ بالله وقُدْرَتِهِ من شَرِّ مَا أَجِدُ واُحَاذِرُ",
        translation: "Place your hand on the part of your body that is in pain and say: 'In the name of Allah' three times, and say seven times: 'I seek refuge in Allah and His power from the evil of what I find and what I guard against.'",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      },
      {
        id: "341",
        title: "What to Say and Do for Sins",
        titleAr: "مايقول ويفعل من أذنب ذنباً",
        arabicText: "مامن عبد يذنب ذنباً فيحسـن الطهور ثم يقوم فيصلي ركعتين ، ثم يستغــفــر الله إلا غفر له",
        translation: "There is no servant who commits a sin, then performs ablution well, then stands and prays two rak'ahs, then seeks forgiveness from Allah, except that he is forgiven.",
        reference: "Sahih Muslim 2715",
        times: 1,
        categoryId: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
        progress: null,
        isBookmarked: false
      }
    ]
  }
}
